<a href="https://colab.research.google.com/github/anapbatista/Fundamentos-em-Ciencia-de-Dados/blob/main/Fundamentos_em_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Primeiros Passos com o Colab**

In [ ]:
print ("Olá mundo, estamos chegando")

Olá mundo, estamos chegando


In [ ]:
nome = input("Digite seu nome: ")
print ( "Meu nome é:", nome)

Digite seu nome: Ana
Meu nome é: Ana


In [ ]:
print ( "Nome é do tipo:", type(nome))

Nome é do tipo: <class 'str'>


In [ ]:
idade = int(input("Digite sua idade: "))
print ( "Tenho", idade, "anos")

Digite sua idade: 23
Tenho 23 anos


In [ ]:
print ( "Idade é do tipo:", type(idade))

Idade é do tipo: <class 'int'>


In [ ]:
x=int(3.98)
y=float(2.34)
z=0
print (x+y)
print (x-y)
print (x*y)
print (x**y) #potência
print (x/y)
print (x%y) #resto da divisão
print ('{:.2f}'.format(x%y)) #formatando decimal com 2 casas
print ('{:.3f}'.format(x%y)) #formatando decimal com 3 casas
print (x//y) #parte inteira da divisão

5.34
0.6600000000000001
7.02
13.075663514671058
1.2820512820512822
0.6600000000000001
0.66
0.660
1.0


In [ ]:
texto = "estou estudando ciência de dados"
#essa função coloca a primeira letra da string maiuscula
print (texto.capitalize())

Estou estudando ciência de dados


In [ ]:
r = float(input("Digite o raio do círculo: "))
pi=3.14
perimetro = 2* pi *r
print ('{:.2f}'.format(perimetro))

Digite o raio do círculo: 8
50.24


In [ ]:
import math
r = float(input("Digite o raio do círculo: "))
perimetro = 2* math.pi *r
print ("%.2f" % (perimetro))
print ('{:.2f}'.format(perimetro))
#duas formas de formatação e precisão do float

Digite o raio do círculo: 8
50.27


In [ ]:
x,y = input("digite dois valores e um backspace entre eles").split()
#essa função pega dois valores de entrada e os separa
x = float (x)
y = float (y)
print (x+y)

digite dois valores e um backspace entre eles2 6
8.0


In [ ]:
#verificar se o argumento inclui apenas caracteres do alfabeto
x = input()
x.isalpha()

2


False

In [ ]:
s = "12345"
print(s.isdecimal())

# contains alphabets
s = "12geeks34"
print(s.isdecimal())

# contains numbers and spaces
s = "12/34"
print(s.isdecimal())

#verificar se todos os caracteres de uma string são dígitos decimais.
#Em outras palavras, ele retorna True se todos os caracteres da string forem números de 0 a 9 e se a string não estiver vazia.

True
False
False


In [ ]:
list1 = ['geeks','for','geeks',2022]
# printing length of list1
print(len(list1))

tuple1 = (1,2,3,4)
# printing length of tuple1
print(len(tuple1))

string1 = "geeksforgeeks"
# printing length of string1
print(len(string1))

#o número total de caracteres em uma string

4
4
13


In [ ]:
string = '123ayu456'
print(string.isnumeric())

string = '123456'
print(string.isnumeric())

#verifica se todos os caracteres da cadeia de caracteres são caracteres numéricos.

False
True


In [ ]:
#vamos dar início a calculadora

x,y = input("digite dois valores: ").split()

if (x.isnumeric() and y.isnumeric()):
  op = input("digite a operação: ")
  if (op=="+"):
    print(float(x)+float(y))
  elif (op=="-"):
    print(float(x)-float(y))
  elif (op=="*"):
    print(float(x)*float(y))
  elif (op=="/"):
    print(float(x)/float(y))
  else:
    print ("Atenção: os valores de operação não são válidos")
else:
  print ("Atenção: os valores de entrada não são numéricos")



digite dois valores: 2 6
digite a operação: p
Atenção: os valores de operação não são válidos


In [ ]:
a = int(input("Digite um número para descobrir o seu fatorial:"))
print (math.factorial(a))

Digite um número para descobrir o seu fatorial:5
120


In [ ]:
#fazendo calculo do fatorial de um numero sem biblioteca

x = int(input("Digite um valor: "))
fatorial = 1

for i in range (x-1):
  fatorial = fatorial * x
  x-=1

print("O fatorial de {} é {}".format(x, fatorial))



Digite um valor: 5
O fatorial de 1 é 120


In [ ]:
#trabalhando com listas (conceitos principais)

lista1=[ "Ana", "Paula", "de", "Abreu", 1.66, 23, 39, 66]

print(len(lista1)) #quantidade de itens dentro da lista

lista1.append(42) #insere objeto no final da lista por padrão
lista1.append("%")
print(lista1)

lista1.insert(4,"Batista") #insere o objeto em uma casa específica da lista (inicia na casa 0)
print(lista1)

lista1.remove("%") #remove apenas a primeira ocorrência do objeto
print(lista1)

lista2=lista1[0:5] #divide a lista de acordo com as casas selecionadas
lista3=lista1[5:10]
print(lista2)
print(lista3)

lista3.sort() #coloca em ordem os objetos de uma lista
lista2.sort() #coloca as strings em ordem alfábetica, do maiusculo para o minusculo
print(lista3)
print(lista2)





8
['Ana', 'Paula', 'de', 'Abreu', 1.66, 23, 39, 66, 42, '%']
['Ana', 'Paula', 'de', 'Abreu', 'Batista', 1.66, 23, 39, 66, 42, '%']
['Ana', 'Paula', 'de', 'Abreu', 'Batista', 1.66, 23, 39, 66, 42]
['Ana', 'Paula', 'de', 'Abreu', 'Batista']
[1.66, 23, 39, 66, 42]
[1.66, 23, 39, 42, 66]
['Abreu', 'Ana', 'Batista', 'Paula', 'de']
['Ana', 'Paula', 'de', 'Abreu', 'Batista', 1.66, 23, 39, 66, 42]


In [ ]:
#criando um sistema de votação que soma os votos e mostra o resultado dos votos

dicio={1: ("José Alves", 19),
       2: ("Maria Antonieta", 15),
       3: ("Carlos Augusto", 63),
       4: ("Luiz Nando", 32)}

print(dicio[1]) #printando um valor do dicionário pela chave

print(dicio.keys()) #printando chaves do dicionario

print(dicio.values()) #printando valores do dicionário

d = int(input("digite o valor do seu candidato "))

if d in dicio: #verificando se existe alguma chave com esse valor
  valor=dicio[d]
  t=int(valor[1])
  t+=1
  dicio[d]=(valor[0],t)

print(dicio.values())



('José Alves', 19)
dict_keys([1, 2, 3, 4])
dict_values([('José Alves', 19), ('Maria Antonieta', 15), ('Carlos Augusto', 63), ('Luiz Nando', 32)])
digite o valor do seu candidato 3
dict_values([('José Alves', 19), ('Maria Antonieta', 15), ('Carlos Augusto', 64), ('Luiz Nando', 32)])


In [ ]:
#criando função(módulo) média

def media():
  quant=int(input("digite quantos valores deseja calcular a media "))
  soma=0
  num=quant
  resultado=0

  while num!=0:
    n=int(input("digite um valor "))
    num=num-1
    soma=soma+n

  return (soma/quant)

resultado=media()
print(resultado)

f=open('calculosdamedia.txt', 'w')
f.write(str(resultado))
f.close()

digite quantos valores deseja calcular a media 2
digite um valor 1
digite um valor 3
2.0


In [ ]:
#iniciando importação de bibliotecas - NUMPY
import numpy as np #convenção

inteiros = np.array ({1,2,3})
reais = np.array([[3.14, 2.65, 9.41], [5.6, 2.9, 3.7]])

print(reais[0]) #acessando a posição da matriz

print(reais[0,1]) #acessando elemento

print(reais.dtype) #vendo o tipo da matriz

a = np.array([2])
b = np.array([1,2,3])
c = np.array([[3.14, 2.65, 9.41], [5.6, 2.9, 3.7]])
d = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])

print(a.shape) #mostra o formato da matriz, linhas, colunas
print(b.shape)
print(c.shape)
print(d.shape)
print(d[0].shape) #mostra o formato de uma matriz dentro da matriz

print(d.ndim) #qual a dimensão da matriz

e = np.array([1,2,3], dtype=float) #transformando em float
f = np.array([3,4,5])
print(e)

print(f.astype(float)) #printa como float
print(f) #mas não altera o tipo de dado da matriz
print(d.reshape([2,6])) #mudando o formato da matriz


print(d.size) #numero de elementos de uma matriz


#criando uma matriz com especificações

m1 = np.arange(5,25,5).reshape(2,2) #cria uma linha iniciando em 5, até o número 20, de 5 em 5 (em formato 2 por 2)
m2 = np.ones([3,2], dtype=int) #matriz com todos os elementos sendo 1, no formato 3 linhas e 2 colunas
m3 = np.empty([5,5,3]) #cria uma matriz com elementos formados por lixo na memória (5 matrizes internas, 5 linhas, 3 colunas)
print(m1)
print(m2)
print(m3)

print()
print(np.random.rand(3,3)) #elementos de 0 a 1 (3 por 3)
print()
print((np.random.rand(3,3)*10)+10)

t=b+10
print(t)


m3=np.array([[3,4],[3,4]])
m4=np.array([[3,4],[3,4],[3,4]])
print()
print(np.matmul(m4,m3)) #produto matricial
print(e*f) #multiplica elemento por elemento
print(m4)
print(m4.sum(axis=0)) #soma dos elementos das colunas
print(m4.sum(axis=1)) #soma dos elementos das linhas

[3.14 2.65 9.41]
2.65
float64
(1,)
(3,)
(2, 3)
(2, 2, 3)
(2, 3)
3
[1. 2. 3.]
[3. 4. 5.]
[3 4 5]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]
12
[[ 5 10]
 [15 20]]
[[1 1]
 [1 1]
 [1 1]]
[[[5.03560581e-310 0.00000000e+000 2.71242040e-321]
  [            nan 1.12646967e-321 0.00000000e+000]
  [2.21525952e+214 1.15989825e+253 3.42134148e+180]
  [1.15313522e+214 5.29877267e+180 5.98129759e-154]
  [1.81786189e+185 1.91077771e+214 5.03032220e+180]]

 [[1.06400250e+248 2.35052608e+180 5.30586801e+180]
  [4.96036526e+180 1.46923002e+195 5.29877267e+180]
  [6.01334515e-154 6.20428116e+223 2.03196437e+174]
  [1.68821597e+195 1.74928933e+243 9.75025264e+199]
  [1.47716621e+248 3.73944688e+193 6.01334434e-154]]

 [[1.62348178e+219 2.25538745e+276 5.84938624e+199]
  [4.72883470e+164 1.99722429e+161 9.30860842e+199]
  [9.19596627e+170 4.38302239e+156 1.47716517e+248]
  [7.68252167e+170 6.01346954e-154 6.01434482e+175]
  [9.80727463e+256 5.70951142e+228 1.33073579e+179]]

 [[2.31461381e-152 7.68252156e+170 1.999152

In [ ]:
#iniciando importação de bibliotecas - PANDAS

import numpy as np
import pandas as pd

serie = pd.Series(['Rodolfo','Nonato','Simoes','Rudinei'], index=[12, 23, 34, 10]) #criando uma série com chave
display(serie)
print()
display(serie.iloc[2]) #acessando pelo índice do vetor
print()
display(serie.loc[12]) #acessando pelas chaves(index)
print()

dicio= {'a': 10,
        'b': 8,
        'c': 5,}

serie2= pd.Series(dicio) #transformando um dicionário em série (mais fácil de manipular)
display(serie2)
print()
display(serie2[:2]) #acessando posições de 0 a 1
print()


serie3= pd.Series(np.arange(10)*2) #criando uma serie de 0 a 9, com valores multiplicado por 2
display(serie3)
print()


npa= np.array([
    ['Rodolfo','Nonato','Simoes','Rudinei'],
    [12, 23, 34, 10],
    [2, 3, 4, 0],
    [75, 80, 60, 80]])

display(npa)
print()
man= pd.DataFrame(npa.T, columns=['Nome','P1', 'P2', 'Frequencia'], index=[123, 598, 784, 964]) #transformando em frame
display(man)
print()


dado=man.loc[123] #acessando o dataframe pela chave
display(dado["Nome"])
print()
display(man.iloc[1]) #acessando posição 1 do dataframe
print()


dicio2= {'nUSP': [123, 598, 784, 964],
    'Nome': ['Rodolfo','Nonato','Simoes','Rudinei'],
    'Curso': ['BCDADOS', 'BECD','BSI', 'BCC'],
    'MediaPonderada': [8.0, 7.5, 7.8, 6.8]}

df=pd.DataFrame(dicio2)
display(df)
print()
display(df['nUSP'])
display(df.query("MediaPonderada >=7.0")) #outra opção ---> retorno = df['MediaPonderada'] >= 7.0
print()

display(df['MediaPonderada'].mean()) #media dos valores
df[df['Curso']!='BCDADOS']['MediaPonderada'].mean() #primeiro conchete -> filtra o curso, segundo conchete -> calcula a media das medias ponderadas desse filtro feito
df.query("Curso!='BSI'")['MediaPonderada'].mean()

12    Rodolfo
23     Nonato
34     Simoes
10    Rudinei
dtype: object

'Simoes'

'Rodolfo'

a    10
b     8
c     5
dtype: int64

a    10
b     8
dtype: int64

0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
9    18
dtype: int64

array([['Rodolfo', 'Nonato', 'Simoes', 'Rudinei'],
       ['12', '23', '34', '10'],
       ['2', '3', '4', '0'],
       ['75', '80', '60', '80']], dtype='<U21')

Nome  P1 P2 Frequencia
123  Rodolfo  12  2         75
598   Nonato  23  3         80
784   Simoes  34  4         60
964  Rudinei  10  0         80

'Rodolfo'

Nome          Nonato
P1                23
P2                 3
Frequencia        80
Name: 598, dtype: object

nUSP     Nome    Curso  MediaPonderada
0   123  Rodolfo  BCDADOS             8.0
1   598   Nonato     BECD             7.5
2   784   Simoes      BSI             7.8
3   964  Rudinei      BCC             6.8

0    123
1    598
2    784
3    964
Name: nUSP, dtype: int64

nUSP     Nome    Curso  MediaPonderada
0   123  Rodolfo  BCDADOS             8.0
1   598   Nonato     BECD             7.5
2   784   Simoes      BSI             7.8

7.525

7.433333333333334

In [ ]:
#iniciando com um dataset

df_califa= pd.read_csv('sample_data/california_housing_train.csv',delimiter=',')
display(df_califa)

df_califa['total_bedrooms'].mean()
df_califa.median()-df_califa.mean()
df_califa.loc[8]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

longitude              -114.5900
latitude                 33.6100
housing_median_age       34.0000
total_rooms            4789.0000
total_bedrooms         1175.0000
population             3134.0000
households             1056.0000
median_income             2.1782
median_house_value    58400.0000
Name: 8, dtype: float64

In [ ]:
import numpy as np    #calculando distância euclidiana
import pandas as pd


dicio = {
  'idade' :[12,13,18],
  'media' :[8,7,9],
  'tempoLOL' :[110,130,135]
}

df = pd.DataFrame(dicio)
dif=df['media']-df['tempoLOL']
quad=np.dot(dif,dif)
finalMediaTempo=np.sqrt(quad)
display(finalMediaTempo)

dif=df['idade']-df['media']
quad=np.dot(dif,dif)
finalMediaIdade=np.sqrt(quad)
display(finalMediaIdade)

dif=df['idade']-df['tempoLOL']
quad=np.dot(dif,dif)
finalIdadeTempo=np.sqrt(quad)
display(finalIdadeTempo)


203.49201458533943

11.532562594670797

192.30704615276062